### ISSUE TITLE
Google Sign-In issue

### ISSUE THREAD

**Issue by damienissa** [serverpod/serverpod#1002]
**Describe the bug**
When I try to login from Android app, I received:
```
METHOD CALL: serverpod_auth.google.authenticateWithServerAuthCode duration: 259ms numQueries: 0 authenticatedUser: null
Failed to obtain access credentials. Error: unauthorized_client Unauthorized Status code: 401
#0      ClientExtensions.requestJson (package:googleapis_auth/src/utils.dart:101:7)
<asynchronous suspension>
#1      obtainAccessCredentialsViaCodeExchange (package:googleapis_auth/src/oauth2_flows/auth_code.dart:115:19)
<asynchronous suspension>
#2      _GoogleUtils.clientViaClientSecretAndCode (package:serverpod_auth_server/src/endpoints/google_endpoint.dart:230:23)
<asynchronous suspension>
#3      GoogleEndpoint.authenticateWithServerAuthCode (package:serverpod_auth_server/src/endpoints/google_endpoint.dart:33:22)
<asynchronous suspension>
#4      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:111:20)
<asynchronous suspension>
#5      Server._handleRequest (package:serverpod/src/server/server.dart:243:18)
<asynchronous suspension>
```

**Serverpod versions**
 - serverpod version: 1.1.1
 - serverpod: ^1.1.1
 - serverpod_auth_server: ^1.1.1
 
How I can fix that?

**Comment by damienissa** [comment]
Also, when I changed the previous problem by my hand. I had a new issue:

<img width="1032" alt="image" src="https://github.com/serverpod/serverpod/assets/17296142/2cab27a7-e263-40f7-b2d2-1c2fbe9a019d">

My `data['aud']` is not the same as `clientId`. I think it happens by adding Firebase. But I already have all the necessary info from Google! 

How I can fix that?

**Comment by damienissa** [comment]
Hi, @vlidholt any ideas on it?

**Comment by damienissa** [comment]
Also, when I try to login from Android app, I received:
```
METHOD CALL: serverpod_auth.google.authenticateWithServerAuthCode duration: 259ms numQueries: 0 authenticatedUser: null
Failed to obtain access credentials. Error: unauthorized_client Unauthorized Status code: 401
#0      ClientExtensions.requestJson (package:googleapis_auth/src/utils.dart:101:7)
<asynchronous suspension>
#1      obtainAccessCredentialsViaCodeExchange (package:googleapis_auth/src/oauth2_flows/auth_code.dart:115:19)
<asynchronous suspension>
#2      _GoogleUtils.clientViaClientSecretAndCode (package:serverpod_auth_server/src/endpoints/google_endpoint.dart:230:23)
<asynchronous suspension>
#3      GoogleEndpoint.authenticateWithServerAuthCode (package:serverpod_auth_server/src/endpoints/google_endpoint.dart:33:22)
<asynchronous suspension>
#4      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:111:20)
<asynchronous suspension>
#5      Server._handleRequest (package:serverpod/src/server/server.dart:243:18)
<asynchronous suspension>
```

**Comment by damienissa** [comment]
Fixed by providing `serverClientId` to `signInWithGoogle` method.
