### ISSUE TITLE
Analytics server being down leads to fail on create

### ISSUE THREAD

**Issue by robiness** [serverpod/serverpod#109]
On `serverpod create` i get a `Unhandled exception`. `mixpanel.com` is currently down. Maybe this shouldn't prevent us from creating a project?

Nice project though and looking forward to use it!

```
SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = api.mixpanel.com, port = 50692
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:237:22)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:60:28)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2438:24)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2834:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2839:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2698:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2570:7)
#10     IOClient.send (package:http/src/io_client.dart:35:38)
#11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
#12     BaseClient.post (package:http/src/base_client.dart:32:7)
#13     post.<anonymous closure> (package:http/http.dart:69:16)
#14     _withClient (package:http/http.dart:164:20)
#15     post (package:http/http.dart:68:5)
#16     Analytics.track (file:///Users/robin/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.5/bin/analytics/analytics.dart:31:28)
#17     main (file:///Users/robin/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.5/bin/serverpod_cli.dart:204:16)
<asynchronous suspension>
```

**Comment by vlidholt** [comment]
Thanks! Will fix in the next update

**Comment by vlidholt** [comment]
Fixed
