### ISSUE TITLE
Error on `serverpod generate` after changing project name

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1131]
**Describe the bug**

I renamed my serverpod directories and renamed the project, using a global search/replace in all files. I then ran `generate_all` in the serverpod project (based on `git main` version).

After that, when I run `serverpod generate`, I get this:

```console
Analyzing the endpoints.
Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if you filed an issue over at Github. Please include the stack trace below and describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues
Null check operator used on a null value
#0      new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:75:53)
#1      EndpointsAnalyzer.analyze (package:serverpod_cli/src/analyzer/dart/endpoints_analyzer.dart:140:42)
<asynchronous suspension>
#2      performGenerate (package:serverpod_cli/src/generator/generator.dart:46:19)
<asynchronous suspension>
#3      _main (file:///home/luke/Work/myproj/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:282:7)
<asynchronous suspension>
#4      main.<anonymous closure> (file:///home/luke/Work/myproj/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:44:9)
<asynchronous suspension>
#5      main (file:///home/luke/Work/myproj/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:41:3)
<asynchronous suspension>
```

`package:serverpod_cli/src/analyzer/dart/endpoints_analyzer.dart:140` is:

```dart
                    type: TypeDefinition.fromDartType(param.type),
```

**Comment by lukehutch** [comment]
I changed a bunch of things, and now this command works fine -- no idea how I fixed it, or what the problem was...
