### ISSUE TITLE
Yikes

### ISSUE THREAD

**Issue by dongri727** [serverpod/serverpod#1240]
I got these message when I'd like just server generate on this project, what can I do for this ?

https://github.com/dongri727/acorn

dart bin/main.dart
lib/server.dart:16:5: Error: Method not found: 'Protocol'.
    Protocol(),
    ^^^^^^^^

Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if
you filed an issue over at Github. Please include the stack trace below and describe any steps you did to trigger the
error.
https://github.com/serverpod/serverpod/issues
Null check operator used on a null value
#0      new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:75:49)
#1      new TypeDefinition.fromDartType.<anonymous closure> (package:serverpod_cli/src/generator/types.dart:70:56)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:47:28)
#7      ListIterable.toList (dart:_internal/iterable.dart:214:7)
#8      new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:70:73)
#9      new TypeDefinition.fromDartType.<anonymous closure> (package:serverpod_cli/src/generator/types.dart:70:56)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#12     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#13     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#14     new List.of (dart:core-patch/array_patch.dart:47:28)
#15     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#16     new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:70:73)
#17     EndpointsAnalyzer.analyze (package:serverpod_cli/src/analyzer/dart/endpoints_analyzer.dart:168:48)
<asynchronous suspension>
#18     performGenerate (package:serverpod_cli/src/generator/generator.dart:46:19)
<asynchronous suspension>
#19     _main (file:///Users/laporte/.pub-cache/hosted/pub.dev/serverpod_cli-1.1.1/bin/serverpod_cli.dart:221:7)
<asynchronous suspension>
#20     main.<anonymous closure> (file:///Users/laporte/.pub-cache/hosted/pub.dev/serverpod_cli-1.1.1/bin/serverpod_cli.dart:36:9)
<asynchronous suspension>
#21     main (file:///Users/laporte/.pub-cache/hosted/pub.dev/serverpod_cli-1.1.1/bin/serverpod_cli.dart:33:3)
<asynchronous suspension>

**Comment by Isakdl** [comment]
Question did you rename any protocol class name? We have a bug where the code generator crashes if you do, see https://github.com/serverpod/serverpod/issues/1169. 

Could you try to delete all generated code and try to regenerate again? Also make sure that all your `endpoint` files are importing the correct datatypes etc. 

Please let me know if this didn't help you!

**Comment by Isakdl** [comment]
No worries :), happy you solved it!
