### ISSUE TITLE
"Yikes!" error if using Dart 3 record types in endpoint definition

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1275]
**Describe the bug**

If I declare an endpoint with a return type of `Future<List<(String, String)>>`, I get the following:

```console
Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if you filed an issue over at Github. Please include the stack trace below and describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues

Null check operator used on a null value

#0      new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:77:53)
#1      new TypeDefinition.fromDartType.<anonymous closure> (package:serverpod_cli/src/generator/types.dart:72:56)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:47:28)
#7      ListIterable.toList (dart:_internal/iterable.dart:214:7)
#8      new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:72:73)
#9      new TypeDefinition.fromDartType.<anonymous closure> (package:serverpod_cli/src/generator/types.dart:72:56)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#12     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#13     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#14     new List.of (dart:core-patch/array_patch.dart:47:28)
#15     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#16     new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:72:73)
#17     EndpointsAnalyzer.analyze (package:serverpod_cli/src/analyzer/dart/endpoints_analyzer.dart:165:48)
<asynchronous suspension>
#18     performGenerate (package:serverpod_cli/src/generator/generator.dart:49:19)
<asynchronous suspension>
#19     GenerateCommand.run (package:serverpod_cli/src/commands/generate.dart:59:22)
<asynchronous suspension>
#20     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#21     ServerpodCommandRunner.runCommand (package:serverpod_cli/src/runner/serverpod_command_runner.dart:137:7)
<asynchronous suspension>
#22     _main (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:51:3)
<asynchronous suspension>
#23     main.<anonymous closure> (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:25:9)
<asynchronous suspension>
#24     main (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:22:3)
<asynchronous suspension>
```

I wasn't really expecting this to work, because it's a new feature of Dart, but the error is a bit jarring nonetheless.

The offending line, `types.dart:77`, is:

```
var className = type is! VoidType ? type.element!.displayName : 'void';
```

**Comment by Isakdl** [comment]
Related issue crashing at the same point: https://github.com/serverpod/serverpod/issues/1169

**Comment by lukehutch** [comment]
I have another crash now, the same cause, out of the box, when compiling `serverpod_test_server`:

```console
serverpod
✅ Done.

examples/chat/chat_server
✅ Done.

\nmodulename_server
✅ Done.

\nprojectname_server
✅ Done.

\nserverpod_auth_server
✅ Done.

\nserverpod_chat_server
✅ Done.

\ntests/serverpod_test_server

Found 1 error.
Error on line 2, column 8 of lib/src/protocol/simple_datatime.yaml: The class name "SimpleDateTime" is already used by another protocol class.
  ╷
2 │ class: SimpleDateTime
  │        ^^^^^^^^^^^^^^
  ╵

Found 1 error.
Error on line 2, column 8 of lib/src/protocol/simple_date_time.yaml: The class name "SimpleDateTime" is already used by another protocol class.
  ╷
2 │ class: SimpleDateTime
  │        ^^^^^^^^^^^^^^
  ╵
Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if you filed an issue over at Github. Please include the stack trace below and describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues

Null check operator used on a null value

#0      new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:77:53)
#1      new TypeDefinition.fromDartType.<anonymous closure> (package:serverpod_cli/src/generator/types.dart:72:56)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:47:28)
#7      ListIterable.toList (dart:_internal/iterable.dart:214:7)
#8      new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:72:73)
#9      new TypeDefinition.fromDartType.<anonymous closure> (package:serverpod_cli/src/generator/types.dart:72:56)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#12     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#13     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#14     new List.of (dart:core-patch/array_patch.dart:47:28)
#15     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#16     new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:72:73)
#17     EndpointsAnalyzer.analyze (package:serverpod_cli/src/analyzer/dart/endpoints_analyzer.dart:165:48)
<asynchronous suspension>
#18     performGenerate (package:serverpod_cli/src/generator/generator.dart:49:19)
<asynchronous suspension>
#19     GenerateCommand.run (package:serverpod_cli/src/commands/generate.dart:59:22)
<asynchronous suspension>
#20     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#21     ServerpodCommandRunner.runCommand (package:serverpod_cli/src/runner/serverpod_command_runner.dart:137:7)
<asynchronous suspension>
#22     _main (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:51:3)
<asynchronous suspension>
#23     main.<anonymous closure> (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:25:9)
<asynchronous suspension>
#24     main (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:22:3)
<asynchronous suspension>

\ntests/serverpod_test_module/serverpod_test_module_server
✅ Done.
```

**Comment by lukehutch** [comment]
Now I can't even build my project, and I don't know what part of my server code is triggering this crash. (I changed only my server code, not code in the serverpod project):

```dart
$ dart ../vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart generate
Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if you filed an issue over at Github. Please include the stack trace below and describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues

Null check operator used on a null value

#0      new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:77:53)
#1      EndpointsAnalyzer.analyze (package:serverpod_cli/src/analyzer/dart/endpoints_analyzer.dart:140:42)
<asynchronous suspension>
#2      performGenerate (package:serverpod_cli/src/generator/generator.dart:49:19)
<asynchronous suspension>
#3      GenerateCommand.run (package:serverpod_cli/src/commands/generate.dart:59:22)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      ServerpodCommandRunner.runCommand (package:serverpod_cli/src/runner/serverpod_command_runner.dart:137:7)
<asynchronous suspension>
#6      _main (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:51:3)
<asynchronous suspension>
#7      main.<anonymous closure> (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:25:9)
<asynchronous suspension>
#8      main (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:22:3)
<asynchronous suspension>
```

**Comment by lukehutch** [comment]
OK, so in the last case, I had both an enum and an endpoint in the project that I changed in incompatible ways, and it seems that A couldn't build without B already being generated, and B couldn't build without A already being generated (or something along those lines).

**Comment by Isakdl** [comment]
> I have another crash now, the same cause, out of the box, when compiling serverpod_test_server:

Hmm seems this is cause by a copy paste mistake in our protocol files, using the same class name twice is not all allowed. 

The crashes are indeed from the same place, in the two latest cases because the generated code is missing, (I.E. an invalid import in the endpoint file). This is the bug that needs to be fixed.
