### ISSUE TITLE
"Yikes!" exception in `new TypeDefinition.fromDartType`

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1574]
**Describe the bug**

This was triggered by `serverpod generate --watch` observing a change:

```console
Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if you filed an issue over at Github. Please include the stack trace below and describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues

Null check operator used on a null value

#0      new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:82:53)
#1      EndpointsAnalyzer.analyze (package:serverpod_cli/src/analyzer/dart/endpoints_analyzer.dart:140:42)
<asynchronous suspension>
#2      performGenerate (package:serverpod_cli/src/generator/generator.dart:48:19)
<asynchronous suspension>
#3      StdOutLogger.progress (package:serverpod_cli/src/logger/loggers/std_out_logger.dart:131:20)
<asynchronous suspension>
#4      performGenerateContinuously (package:serverpod_cli/src/generator/generator_continuous.dart:27:15)
<asynchronous suspension>
#5      GenerateCommand.run (package:serverpod_cli/src/commands/generate.dart:68:17)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      ServerpodCommandRunner.runCommand (package:serverpod_cli/src/runner/serverpod_command_runner.dart:137:7)
<asynchronous suspension>
#8      _main (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:51:3)
<asynchronous suspension>
#9      main.<anonymous closure> (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:25:9)
<asynchronous suspension>
#10     main (file:///home/luke/Work/click/vendor/serverpod/tools/serverpod_cli/bin/serverpod_cli.dart:22:3)
<asynchronous suspension>
```

Line in question:

```dart
    var className = type is! VoidType ? type.element!.displayName : 'void';
```

**Comment by Isakdl** [comment]
Related issues:

https://github.com/serverpod/serverpod/issues/1275
https://github.com/serverpod/serverpod/issues/1169
https://github.com/serverpod/serverpod/issues/1390
https://github.com/serverpod/serverpod/issues/1299

Will take a look at this soon, this row of code seems to cause a lot of different bugs.
