### ISSUE TITLE
Error initializing extension

### ISSUE THREAD

**Issue by luisgustavoo** [serverpod/serverpod#1847]
<img width="470" alt="image" src="https://github.com/serverpod/serverpod/assets/59834387/4bdca854-4c4a-4b27-b488-6d42fb5665ff">

```
[Error - 20:13:14] Client Serverpod: connection to server is erroring. Shutting down server.
[Error - 20:13:14] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 20:13:16] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 20:13:16] Connection to server got closed. Server will restart.
true
[Error - 20:13:16] Serverpod client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 20:13:17] Client Serverpod: connection to server is erroring. Shutting down server.
[Error - 20:13:17] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 20:13:19] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 20:13:19] Connection to server got closed. Server will restart.
true
[Error - 20:13:19] Serverpod client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 20:13:20] Client Serverpod: connection to server is erroring. Shutting down server.
[Error - 20:13:20] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 20:13:22] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 20:13:22] Connection to server got closed. Server will restart.
true
[Error - 20:13:22] Serverpod client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 20:13:22] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 20:13:23] Client Serverpod: connection to server is erroring. Shutting down server.
[Error - 20:13:23] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 20:13:25] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 20:13:25] Connection to server got closed. Server will restart.
true
[Error - 20:13:25] Serverpod client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 20:13:25] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 20:13:26] Client Serverpod: connection to server is erroring. Shutting down server.
[Error - 20:13:26] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/Users/luisgustavo/.vscode/extensions/serverpod.serverpod-1.2.2/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 20:13:28] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 20:13:28] The Serverpod server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 20:13:28] Serverpod client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 20:13:28] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

```

**Comment by Isakdl** [comment]
Hey! Do you get any errors when running Serverpod generate?

**Comment by luisgustavoo** [comment]
No

**Comment by vlidholt** [comment]
Can you provide some more information on how you start the server and how you run your client?

**Comment by SandPod** [comment]
Hey @luisgustavoo,

I think we found the root cause of the issue now.

By default we print an update prompt if the latest version of the CLI is not installed. This was also printed when we started the language server which broke the protocol and caused the LSP client to crash.

We have a fix for it not incoming that should also fix the current released extensions.

**Comment by jason-downs** [comment]
I'm still constantly getting this any time I try to edit the .spy files, and I'm up-to-date with latest serverpod and vscode extension versions (fwiw I'm using Cursor not vscode)

**Comment by SandPod** [comment]
@jason-downs - The LSP protocol is really sensitive about anything being printed before the handshake it complete.

Does your Serverpod command, by any chance, always print something regardless of what mode it is started in?
Dart fairly recently made a change that would rebuild a locally activated CLI command on each invocation. This would break the LSP protocol contract since a rebuild automatically prints something to the console.

**Comment by jason-downs** [comment]
Hi @SandPod I'm not printing anything to the console when I get this...actually I get this popup error whenever I edit any .spy yaml files (like just a simple thing like typing in the file in Cursor editor will trigger this) instead of on initialization, so maybe it's not entirely accurate for me to have posted in this particular issue, but I do get the same popup error in the editor. See my issue #3719  - specifically, after I get the "connection has closed" error several times, I then get the error in this issue that it has crashed too many times and will not be restarted.

**Comment by SandPod** [comment]
@jason-downs - Thanks for filing a separate issue for this, we can continue the conversation there 👍
