### ISSUE TITLE
Doc update request: explaining `serverpod_auth_google: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)`

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#2232]
This exception took me a long time to find an explanation for:

```dart
I/flutter (29719): serverpod_auth_google: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
I/flutter (29719): #0      GoogleSignInApi.signIn (package:google_sign_in_android/src/messages.g.dart:221:7)
I/flutter (29719): <asynchronous suspension>
I/flutter (29719): #1      GoogleSignInAndroid._signInUserDataFromChannelData (package:google_sign_in_android/google_sign_in_android.dart:111:3)
I/flutter (29719): <asynchronous suspension>
I/flutter (29719): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:278:30)
I/flutter (29719): <asynchronous suspension>
I/flutter (29719): #3      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:431:5)
I/flutter (29719): <asynchronous suspension>
```

The reason for this cryptic error is that the SHA-1 key for the OAuth2 configuration in the Google Developer Console did not match the SHA-1 signature of the key used to sign the app (which can be seen using `./gradlew signingReport` in the `android` sub-project of the app source).

**Comment by marcelomendoncasoares** [comment]
Closing since this is related to the legacy auth, which is no longer receiving updates.

**Comment by lukehutch** [comment]
@marcelomendoncasoares this error comes from the Google OAuth2 API, not the old Serverpod auth system. It is one of the most aggravatingly frustrating things to have to figure out when setting up Google OAuth for any project. There are many thousands of complaints about this online, but of course Google doesn't care. This is not at all limited to Serverpod, but Serverpod could help its users by explaining the possible sources of this error. Please reopen.

**Comment by marcelomendoncasoares** [comment]
@lukehutch On the new auth, this issue is actually contemplated. On the [Android configuration section](https://docs.serverpod.dev/next/concepts/authentication/providers/google/setup#android) we detail how to generate the SHA, the different procedure to get the SHA key for production and even refer to the [official troubleshooting guide](https://pub.dev/packages/google_sign_in_android#troubleshooting) for further assistance.
