### ISSUE TITLE
issue with setUserImage on serverpod_auth_client module

### ISSUE THREAD

**Issue by tylersavery** [serverpod/serverpod#2331]
**Describe the bug**
When hitting the client.modules.auth.user.setUserImage(image), a 400 error is being returned.

**To Reproduce**
1. Add the serverpod_auth_client module
2. Convert an image to bytes
3. Use the `client.modules.auth.user.setUserImage(image)` function

**Expected behavior**
200 Success (with a boolean of true or false coming back)

**Serverpod versions**
 -  _CLI Version:_ 2.0.0
 - _Library version:_ 2.0.0

**Platform information**
I've tried on iOS and web with the same results.

**Additional context**
I believe this could be related to server.dart in the core framework. See the block starting at line 269. At 287, there is a null override (!) on the value body, but body can technically be null if `await _readBody(request);` comes back null.

This likely isn't the root of the problem but something I identified while stepping through.

Additionally, I'll add, I have tried this with both the built in storage AND the S3 module.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ServerpodClientException: , statusCode = 400
#0      ServerpodClient.callServerEndpoint (package:serverpod_client/src/serverpod_client_io.dart:73:9)
<asynchronous suspension>
#1      _SettingsScreenState.build.<anonymous closure>.<anonymous closure> (package:spmc_flutter/src/screens/settings_screen.dart:96:45)
<asynchronous suspension>
```

**Comment by SandPod** [comment]
Hey @tylersavery!

Thanks for the report.
What logs are you getting from the Server when processing this request?
If you run the server with `--logging=verbose`, do you get any additional information printed then as well?

Please post the server logs if possible :)

**Comment by SandPod** [comment]
@binemmanuel, @tylersavery Are any of you still encountering this issue? We have made some hardening around requests recently.

**Comment by binemmanuel** [comment]
Works fine now.

ServerPod 2.3.0
Dart 3.6.0 (stable) macos_arm64
