### ISSUE TITLE
Improve the error description when passwords.yaml is missing

### ISSUE THREAD

**Issue by Katekko** [serverpod/serverpod#2501]
**Is your feature request related to a problem? Please describe.**

When the passwords file is missing, the application encounters a null check operator error. This is not very user-friendly. It would be more helpful to display a clear and concise error message to the user, indicating that the passwords file is missing. 

This is the error when the file isn´t created
```
katekko@katekko:~/Projects/poke_arena/poke_arena_server$ dart bin/main.dart --apply-migrations
Failed to load config: Null check operator used on a null value
Unhandled exception:
Null check operator used on a null value
#0      new DatabaseConfig._fromJson (package:serverpod_shared/src/config.dart:226:38)
#1      new ServerpodConfig.load (package:serverpod_shared/src/config.dart:94:35)
#2      Serverpod._loadConfig (package:serverpod/src/server/serverpod.dart:403:32)
#3      new Serverpod (package:serverpod/src/server/serverpod.dart:300:19)
#4      run (package:poke_arena_server/server.dart:9:15)
#5      main (file:///home/katekko/Projects/poke_arena/poke_arena_server/bin/main.dart:6:3)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Describe the solution you'd like**

Instead of the null check operator error, the application should display a specific error message, such as "Passwords file not found." This message should be clear and actionable, allowing the user to understand the issue and take appropriate action, like providing the missing file.

-------
Obs. I remember seeing an issue about this, but I wasn't able to locate it.

**Comment by Katekko** [comment]
I guess a found it: https://github.com/serverpod/serverpod/issues/2294

Its not release yet
