### ISSUE TITLE
Module creation gives wrong running docs

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#257]
## Description
When I try to create a module demo code, It gives me the wrong procedure to run the code.

## Logs
```console
minnu@MrMinnus-MacBook-Air Desktop % serverpod create -t module module_demo
Creating project module_demo...
  /Users/minnu/Desktop/module_demo/module_demo_server/generated/protocol.yaml
  /Users/minnu/Desktop/module_demo/module_demo_server/generated/tables.pgsql
  /Users/minnu/Desktop/module_demo/module_demo_server/CHANGELOG.md
  /Users/minnu/Desktop/module_demo/module_demo_server/config/generator.yaml
  /Users/minnu/Desktop/module_demo/module_demo_server/README.md
  /Users/minnu/Desktop/module_demo/module_demo_server/pubspec.yaml
  /Users/minnu/Desktop/module_demo/module_demo_server/setup-tables
  /Users/minnu/Desktop/module_demo/module_demo_server/lib/module.dart
  /Users/minnu/Desktop/module_demo/module_demo_server/lib/src/generated/endpoints.dart
  /Users/minnu/Desktop/module_demo/module_demo_server/lib/src/generated/protocol.dart
  /Users/minnu/Desktop/module_demo/module_demo_server/lib/src/generated/module_class.dart
  /Users/minnu/Desktop/module_demo/module_demo_server/lib/src/endpoints/module_endpoint.dart
  /Users/minnu/Desktop/module_demo/module_demo_server/lib/src/protocol/module_class.yaml
  /Users/minnu/Desktop/module_demo/module_demo_server/analysis_options.yaml
  /Users/minnu/Desktop/module_demo/module_demo_server/gitignore
  /Users/minnu/Desktop/module_demo/module_demo_client/pubspec.yaml
  /Users/minnu/Desktop/module_demo/module_demo_client/lib/module.dart
  /Users/minnu/Desktop/module_demo/module_demo_client/lib/src/protocol/client.dart
  /Users/minnu/Desktop/module_demo/module_demo_client/lib/src/protocol/protocol.dart
  /Users/minnu/Desktop/module_demo/module_demo_client/lib/src/protocol/module_class.dart
  /Users/minnu/Desktop/module_demo/module_demo_client/gitignore
Setting up Docker and default database tables in
/Users/minnu/Desktop/module_demo/module_demo_server
If you run serverpod create for the first time, this can take a few minutes as
Docker is downloading the images for Postgres. If you get stuck at this step,
make sure that you have the latest version of Docker Desktop and that it is
currently running.

Completed table setup exit code: 0
Cleaning up



=== SERVERPOD CREATED ===

All setup. You are ready to rock!

Start your Serverpod server by running:

  $ cd module_demo/module_demo_server
  $ docker-compose up --build --detach
  $ serverpod run

You can also start Serverpod manually by running:

  $ cd module_demo/module_demo_server
  $ docker-compose up --build --detach
  $ dart bin/main.dart
```

When I followed the `serverpod run` I go these logs
**Logs**
```console
minnu@MrMinnus-MacBook-Air module_demo_server % serverpod run
Unhandled exception:
FileSystemException: Cannot open file, path = 'config/development.yaml' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      new ServerpodConfig (package:serverpod_shared/src/config.dart:41:27)
#5      new ConfigInfo (file:///Users/minnu/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.10/bin/config_info/config_info.dart:9:14)
#6      performRun (file:///Users/minnu/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.10/bin/run/runner.dart:23:20)
#7      main (file:///Users/minnu/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.10/bin/serverpod_cli.dart:239:9)
<asynchronous suspension>
```

And also I noticed that `config/generator.yaml` and some other files have the wrong configs(After creating a module)
```yaml
type: module

client_package_path: ../MODULENAME_client
```

![Screenshot 2022-09-02 at 9 14 03 PM](https://user-images.githubusercontent.com/35523357/188190641-edd8530a-679b-4d78-b2a3-c30f2a11ebcf.png)

**Comment by vlidholt** [comment]
Fixed
