### ISSUE TITLE
serverpod_auth_google: Failed to authenticate with Serverpod backend. Aborting.

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#259]
## Description
As I'm doing the same in #258, I managed to resolve it, and moving on further, I got into another issue that even though I'm successfully authenticated with google, I still cannot able to log in. As I got these logs(mentioned below). And I followed the traces and debugged the code and I found these things(mentioned in postmortem)

## Logs
```console
Launching lib/main.dart on iPhone 13 in debug mode...
Xcode build done.                                           24.2s
Connecting to VM Service at ws://127.0.0.1:64723/YSj0nwQFG8o=/ws
flutter: serverpod_auth_google: GoogleSignIn
flutter: serverpod_auth_google: serverAuthCode is null. Trying auth.idToken.
flutter: serverpod_auth_google: Failed to authenticate with Serverpod backend. Aborting.
[log] Failed to signin
```

## Postmortem

**signInWithGoogle.serverResponse:**

```
AuthenticationResponse ({"class":"serverpod_auth_server.AuthenticationResponse","data":{"id":null,"success":false,"key":null,"keyId":null,"userInfo":null,"failReason":null}})
```

**result:**

```
GoogleSignInAccount (GoogleSignInAccount:{displayName: Minnu, email: hi2minnu@gmail.com, id: 117033342067198675244, photoUrl: https://lh3.googleusercontent.com/a-/AFdZucpwr0bFHjSHW6xuGe3Dw8GQL3umKTcX5lw4-2oi=s1337, serverAuthCode: null})
```

**idToken:**

```
eyJhbGciOiJSUzI1NiIsImtpZCI6ImU4NDdkOTk0OGU4NTQ1OTQ4ZmE4MTU3YjczZTkxNWM1NjczMDJkNGUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI5MzY2NDM5OTM0MzItbnRicDdncnE3NmdxYWV1M2wzbDIyMGVoOTl0azZhdGwuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI5MzY2NDM5OTM0MzItbnRicDdncnE3NmdxYWV1M2wzbDIyMGVoOTl0azZhdGwuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTcwMzMzNDIwNjcxOTg2NzUyNDQiLCJlbWFpbCI6ImhpMm1pbm51QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiSkJZSFRQVFZTY2FnekpDYWxrNldGZyIsIm5vbmNlIjoiZlB5aTd3cWlSN2dtS1BsTUxyb1NkSkk0YlpkeVB3SmhSUnFIWm1NdVl2byIsIm5hbWUiOiJNaW5udSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQUZkWnVjcHdyMGJGSGpTSFc2eHVHZTNEdzhHUUwzdW1LVGNYNWx3NC0yb2k9czk2LWMiLCJnaXZlbl9uYW1lIjoiTWlubnUiLCJsb2NhbGUiOiJlbi1HQiIsImlhdCI6MTY2MjE0Mjk2NiwiZXhwIjoxNjYyMTQ2NTY2fQ.HkJbzIFrg7g4Lsr0wFt9GLnZeI13X8XIcVx8W-Vm62zS1eFOJ5Kx0nEmSX_jrC1Hy2aWSsyxiYzwE7yNeWLzPu2zgLLb0B1Ia8tUwtrsy1G2GcqzmAgEPcWSjGDyNyOJ427mMkG_kZoW0nRO30xYHWrQtK7J2M05gwMprixN_sH2zhc836iqEQJoNA_KNHns4epjkoaj4rHzOg9_-Olzh8-Cd_krVykmBlUah5EzryvR0OwfjtHvjdeuG514t7qSNvgogm78Q5WXTZEqrvs9xVJjLsHU0T5Nm4KmptqBUgbS--bIcGykNiGN_ekEdOy4hW2CFG-Sm72oo7lCDj_ofA
```

**serverpod_auth.google.authenticateWithIdToken.response:**

```json
{
  "iss": "https://accounts.google.com",
  "azp": "936643993432-ntbp7grq76gqaeu3l3l220eh99tk6atl.apps.googleusercontent.com",
  "aud": "936643993432-ntbp7grq76gqaeu3l3l220eh99tk6atl.apps.googleusercontent.com",
  "sub": "117033342067198675244",
  "email": "hi2minnu@gmail.com",
  "email_verified": "true",
  "at_hash": "JBYHTPTVScagzJCalk6WFg",
  "nonce": "fPyi7wqiR7gmKPlMLroSdJI4bZdyPwJhRRqHZmMuYvo",
  "name": "Minnu",
  "picture": "https://lh3.googleusercontent.com/a-/AFdZucpwr0bFHjSHW6xuGe3Dw8GQL3umKTcX5lw4-2oi=s96-c",
  "given_name": "Minnu",
  "locale": "en-GB",
  "iat": "1662142966",
  "exp": "1662146566",
  "alg": "RS256",
  "kid": "e847d9948e8545948fa8157b73e915c567302d4e",
  "typ": "JWT"
}
```

### Bug to be resolved is

`serverpod_auth_server/lib/src/endpoints/google_endpoint.dart` >> [authenticateWithIdToken (Line#127)](https://github.com/serverpod/serverpod/blob/main/modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/google_endpoint.dart#L127)

### Solution

FROM THIS ==> 
```dart
if(data['iss'] != 'accounts.google.com')
```

TO THIS ==> 
(Preferred)
```dart
if(!data['iss'].contains('accounts.google.com'))
```
or
```dart
if(!['accounts.google.com', 'https://accounts.google.com'].contains(data['iss']))
```

**Comment by vlidholt** [comment]
I think this is working as intended already, but will double check before 1.0 release.

**Comment by yahu1031** [comment]
Will recheck this with the working example and update you.

**Comment by yahu1031** [comment]
@vlidholt A little update as I mentioned in other ticket, I have `GoogleService-Info.plist` in flutter app-Runner and also `google_client_secret.json` in server-config

```console
flutter: serverpod_auth_google: PlatformException(missing-config, GoogleService-Info.plist file not found and clientId was not provided programmatically., null, null)
flutter: #0      StandardMethodCodec.decodeEnvelope  package:flutter/…/services/message_codecs.dart:653  
#1      MethodChannel._invokeMethod                  package:flutter/…/services/platform_channel.dart:296
<asynchronous suspension> 
#2      GoogleSignIn._callMethod                     package:google_sign_in/google_sign_in.dart:271
<asynchronous suspension>
#3      GoogleSignIn.signIn.isCanceled               package:google_sign_in/google_sign_in.dart:407
<asynchronous suspension>
```

Please LMK If I'm missing anything. BTW I'm not using firebase, Only Google OAuth.

**Comment by yahu1031** [comment]
This is only happening in Android for me. I think I saw this with someone else too...

**Comment by vlidholt** [comment]
I went through the whole Sign in with Google over the past days. Everything is working correctly, but documentation wasn't great. I have added to the docs and will release with the next version.

Preview of the new auth docs is here: https://github.com/serverpod/serverpod_docs/blob/main/docs/04-concepts/07-authentication.md
