### ISSUE TITLE
TimeoutException after 0:00:20.000000: Future not completed

### ISSUE THREAD

**Issue by hidayet-poscu** [serverpod/serverpod#2631]
I deployed Serverpod with Google Cloud.
"I am getting a TimeoutException after 0:00:20.000000: Future not completed error on all API requests.

I/flutter (25878): Failed call: serverpod_auth.status.getUserInfo
I/flutter (25878): TimeoutException after 0:00:20.000000: Future not completed

client = Client(

   'https://api.eslimasoftware.site/',
    authenticationKeyManager: FlutterAuthenticationKeyManager(),
  )..connectivityMonitor = FlutterConnectivityMonitor();

..........log........

2024-08-19 20:34:19.105 UTC [4980]: [1-1] db=serverpod,user=postgres ERROR: relation "serverpod_future_call" does not exist at character 13. //
{
httpRequest: {7}
insertId: "bzw1z1f8gd8pv"
jsonPayload: {
@type: "type.googleapis.com/google.cloud.loadbalancing.type.LoadBalancerLogEntry"
backendTargetProjectNumber: "projects/186553975287"
remoteIp: "185.216.203.59"
statusDetails: "body_not_allowed"
}
logName: "projects/eslimasoftwareograsist/logs/requests"
receiveTimestamp: "2024-08-19T19:28:16.091295215Z"
resource: {2}
severity: "WARNING"
timestamp: "2024-08-19T19:28:14.526740Z"

<img width="397" alt="veritabani" src="https://github.com/user-attachments/assets/32a77ab8-5a10-4770-b7de-da232f0bc24a">

.......................
<img width="718" alt="ekran" src="https://github.com/user-attachments/assets/3c965aa7-bd22-49e4-989c-acbbd529a3c0">

**Comment by Isakdl** [comment]
Hey @hidayet-poscu 

This looks strange, but the following `ERROR: relation "serverpod_future_call" does not exist` indicates that the migration is not applied to the cloud database. 

Is the screenshot of the database tables connected to the cloud database?

**Comment by hidayet-poscu** [comment]
> Hey@hidayet-poscu
> 
> Bu garip görünüyor, ancak aşağıdakiler `ERROR: relation "serverpod_future_call" does not exist`göçün bulut veritabanına uygulanmadığını gösteriyor.
> 
> Veritabanı tablolarının ekran görüntüsü bulut veritabanına bağlı mı?

There are no errors in the log records today, but this error occurs in API requests, and the application is not working.

**Comment by donywan** [comment]
Same too,when use `docker build` is use `production.yaml`,but cant' `--apply-migrations`.so,i change  `Docerfile`  `ENTRYPOINT ./server --mode=$runmode --server-id=$serverid --logging=$logging --role=$role --apply-migrations`. I get error ,
```
2024-08-24 09:36:29.303214Z Internal server error. Failed to connect to database in future call manager.
DatabaseException: relation "serverpod_future_call" does not exist
#0      DatabaseConnection._query (package:serverpod/src/database/adapters/postgres/database_connection.dart:404)
<asynchronous suspension>
#1      DatabaseConnection._mappedResultsQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:458)
<asynchronous suspension>
#2      DatabaseConnection._deserializedMappedQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:476)
<asynchronous suspension>
#3      DatabaseConnection.deleteWhere (package:serverpod/src/database/adapters/postgres/database_connection.dart:288)
<asynchronous suspension>
#4      FutureCallManager._checkQueue (package:serverpod/src/server/future_call_manager.dart:107)
<asynchronous suspension>

Local stacktrace:
#0      FutureCallManager._checkQueue (package:serverpod/src/server/future_call_manager.dart:145)
<asynchronous suspension>
```
Only this table can't found.

**Comment by donywan** [comment]
> Same too,when use `docker build` is use `production.yaml`,but cant' `--apply-migrations`.so,i change `Docerfile` `ENTRYPOINT ./server --mode=$runmode --server-id=$serverid --logging=$logging --role=$role --apply-migrations`. I get error ,
> 
> ```
> 2024-08-24 09:36:29.303214Z Internal server error. Failed to connect to database in future call manager.
> DatabaseException: relation "serverpod_future_call" does not exist
> #0      DatabaseConnection._query (package:serverpod/src/database/adapters/postgres/database_connection.dart:404)
> <asynchronous suspension>
> #1      DatabaseConnection._mappedResultsQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:458)
> <asynchronous suspension>
> #2      DatabaseConnection._deserializedMappedQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:476)
> <asynchronous suspension>
> #3      DatabaseConnection.deleteWhere (package:serverpod/src/database/adapters/postgres/database_connection.dart:288)
> <asynchronous suspension>
> #4      FutureCallManager._checkQueue (package:serverpod/src/server/future_call_manager.dart:107)
> <asynchronous suspension>
> 
> Local stacktrace:
> #0      FutureCallManager._checkQueue (package:serverpod/src/server/future_call_manager.dart:145)
> <asynchronous suspension>
> ```
> 
> Only this table can't found.

```
Failed to cleanup closed sessions: DatabaseException: relation "serverpod_session_log" does not exist
#0      DatabaseConnection._query (package:serverpod/src/database/adapters/postgres/database_connection.dart:404)
<asynchronous suspension>
#1      DatabaseConnection.query (package:serverpod/src/database/adapters/postgres/database_connection.dart:342)
<asynchronous suspension>
#2      HealthCheckManager._cleanUpClosedSessions (package:serverpod/src/server/health_check_manager.dart:113)
<asynchronous suspension>
#3      HealthCheckManager._performHealthCheck (package:serverpod/src/server/health_check_manager.dart:76)
<asynchronous suspension>
2024-08-24 13:38:01.095491Z Internal server error. Failed to connect to database in future call manager.
DatabaseException: relation "serverpod_future_call" does not exist
#0      DatabaseConnection._query (package:serverpod/src/database/adapters/postgres/database_connection.dart:404)
<asynchronous suspension>
#1      DatabaseConnection._mappedResultsQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:458)
<asynchronous suspension>
#2      DatabaseConnection._deserializedMappedQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:476)
<asynchronous suspension>
#3      DatabaseConnection.deleteWhere (package:serverpod/src/database/adapters/postgres/database_connection.dart:288)
<asynchronous suspension>
#4      FutureCallManager._checkQueue (package:serverpod/src/server/future_call_manager.dart:107)
<asynchronous suspension>
```

**Comment by donywan** [comment]
`dart complie exe` does not create tables when running in a production environment.You need to execute the sql in the `migrations` directory. This is my understanding

**Comment by migalv** [comment]
I have the same issue. I just followed the [Google Cloud Engine with Terraform](https://docs.serverpod.dev/deployments/deploying-to-gce-terraform) guide. I ran the `migrations/<LATEST_MIGRATION>/definition.sql` from Postico. 

I checked from Postico and the `serverpod_future_call` table actually exists

**Comment by SandPod** [comment]
@hidayet-poscu - Is this still an issue?
