### ISSUE TITLE
DATABASE EXCEPTION: cannot execute INSERT in a read-only transaction When READ ONLY DATABASE CONNECTED

### ISSUE THREAD

**Issue by harasitCS** [serverpod/serverpod#2757]
**Describe the bug**
If i connect a readable PostgreSQL database Then  following error happening
LOG ERRORS
DatabaseException: cannot execute INSERT in a read-only transaction
#0      DatabaseConnection._query (package:serverpod/src/database/adapters/postgres/database_connection.dart:407:9)
<asynchronous suspension>
#1      DatabaseConnection._mappedResultsQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:473:18)
<asynchronous suspension>
#2      DatabaseConnection.insert (package:serverpod/src/database/adapters/postgres/database_connection.dart:142:9)
<asynchronous suspension>
#3      DatabaseConnection.insertRow (package:serverpod/src/database/adapters/postgres/database_connection.dart:155:18)
<asynchronous suspension>
#4      DatabaseLogWriter._databaseLog (package:serverpod/src/server/log_manager/log_writers.dart:153:18)
<asynchronous suspension>
#5      DatabaseLogWriter.openLog (package:serverpod/src/server/log_manager/log_writers.dart:129:21)
<asynchronous suspension>
#6      CachedLogWriter.closeLog (package:serverpod/src/server/log_manager/log_writers.dart:58:5)
<asynchronous suspension>
#7      SessionLogManager.finalizeLog (package:serverpod/src/server/log_manager/log_manager.dart:336:16)
<asynchronous suspension>
#8      Session.close (package:serverpod/src/server/session.dart:231:14)
<asynchronous suspension>
#9      Server._handleUriCall (package:serverpod/src/server/server.dart:530:7)
<asynchronous suspension>
#10     Server._handleRequest (package:serverpod/src/server/server.dart:293:18)
<asynchronous suspension>
#11     Server._handleRequestWithErrorBoundary (package:serverpod/src/server/server.dart:182:5)
<asynchronous suspension>

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup a master(CRUD OPERATION) slave(Readable Only) PostgreSQL database server
2. Connect to slave database(Readable Only) to get any set of data.

**Expected behaviour**
Please provide a configurable setup to write data in serverpod_query_log table and others.

**Serverpod versions**
 -  2.1.1

**Platform information**
UBUNTU 22.04.4 LTS

**Comment by Isakdl** [comment]
If I understand this correctly, the problem is that Serverpod does not support a read-only replica as we write logs and healthchecks to the database. 

The real problem then is to support reading from one instance and writing to another, have I understood the issue correctly?

**Comment by harasitCS** [comment]
Yes.

**Comment by SandPod** [comment]
@harasitCS Is it OK if I convert the title of this issue to "Support read-only replica databases"?
I see this as more of a feature request than a bug.

**Comment by harasitCS** [comment]
Ok.No problem.
Need a solution .
