### ISSUE TITLE
Serialization Error: Unable to Serialize List<CustomSerializableClass> in Stream Response

### ISSUE THREAD

**Issue by AndryHTC** [serverpod/serverpod#2796]
**Describe the bug**
When attempting to listen to a stream from the client, an internal server error occurs related to serialization. The error message indicates that the Serverpod serialization manager cannot find the class name for `List<HistoryEntity>`.

**To Reproduce**
1. Implement the `HistoryEndpoint` with the `snapshot` method as shown below.
2. Implement the `HistoryPrismaRepository` with the `snapshot` method as provided.
3. From the client, subscribe to the `snapshot` stream.
4. Observe the internal server error in the server logs.

**Endpoint Code:**
```dart
class HistoryEndpoint extends Endpoint { 
  Stream<List<HistoryEntity>> snapshot(Session session, HistoryGetPayload payload) {
    return HistoryPrismaRepository.snapshot(
      payload,
    );
  }
}
```

**Repository Code:**
```dart
abstract class HistoryPrismaRepository { 
  static Stream<List<HistoryEntity>> snapshot(HistoryGetPayload payload) {
    // Create a StreamController
    late StreamController<List<HistoryEntity>> controller;
    DateTime? lastUpdate;
    bool isFetching = false;

    void startFetching() async {
      // This function is responsible for fetching data and adding it to the stream
      while (!controller.isClosed && controller.hasListener && !controller.isPaused) {
        if (isFetching) {
          // Prevent fetching if the previous fetch hasn't completed
          await Future.delayed(const Duration(milliseconds: 100));
          continue;
        }
        isFetching = true;

        try {
          if (lastUpdate != null) {
            // Check for new data only after a certain interval
            await Future.delayed(const Duration(seconds: 2));
            var needUpdate =
                await hasNewData(payload: payload, lastUpdate: lastUpdate!);
            if (!needUpdate) {
              isFetching = false;
              continue;
            }
          }

          // Fetching new data
          lastUpdate = DateTime.now();
          var histories = await get(payload);
          controller.add(histories); // Adding fetched data to the stream
        } catch (e) {
          controller.addError(e); // Adding error to the stream
        } finally {
          isFetching = false;
        }
      }
    }

    void onListen() {
      startFetching(); // Start fetching data when stream subscription begins
    }

    void onCancel() async {
      controller
          .close(); // Properly close the controller when the stream is cancelled
    }

    // Initializing the StreamController
    controller = StreamController<List<HistoryEntity>>(
      onListen: onListen,
      onCancel: onCancel,
    );

    return controller.stream;
  } 
}
```

**Error Message:**
```
2024-10-01 15:25:20.948446Z Internal server error. Zoned exception.
Invalid argument(s): Could not find class name for List<HistoryEntity> in serialization.
#0      SerializationManager.wrapWithClassName (package:serverpod_serialization/src/serialization.dart:184:7)
#1      MethodStreamMessage.buildMessage (package:serverpod_serialization/src/websocket_messages.dart:444:32)
#2      _MethodStreamManager._createOutputController.<anonymous closure> (package:serverpod/src/server/websocket_request_handlers/method_websocket_request_handler.dart:473:46)
#3      _rootRunUnary (dart:async/zone.dart:1407:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#7      _DelayedData.perform (dart:async/stream_impl.dart:541:14)
#8      _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
#9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
#10     _rootRun (dart:async/zone.dart:1391:47)
#11     _CustomZone.run (dart:async/zone.dart:1301:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#14     _rootRun (dart:async/zone.dart:1399:13)
#15     _CustomZone.run (dart:async/zone.dart:1301:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

**Expected behavior**
The client should successfully listen to the `snapshot` stream and receive updates of type `List<HistoryEntity>` without encountering serialization errors.

**Serverpod versions**
-  _CLI Version:_ 2.1.2
-  _Library version:_ 2.1.2

**Platform information**
- **Server:** Docker
- **Client Device:** web browser
- **Operating System:** Windows 11
---

**Comment by SandPod** [comment]
Thank you for the detailed report @AndryHTC!

We currently do not have support for nested structures in the streaming interface.
That is `Map`, `List` or `Set`.

### Workaround
To get around this limitation, define a Serverpod model that only contains a list of your custom model and send that model over the stream instead.

```yaml
class: HistorySnapshot
fields:
  snapshot: List<HistoryEntity>
```

The serialization layer will be able to serialize The `HistorySnapshot` model.

The reason this is required is that we need to some meta information to know how to unpack the message when deserializing the message.

### Feature request
If you would like to have this feature in Serverpod, please convert this to a feature request.

### Endpoint analyzer fix
We should probably add some validation that informs you that nested structures are not supported in the streaming interface.

**Comment by AndryHTC** [comment]
OK! I'll try it soon, thank you very much.

**Comment by AndryHTC** [comment]
Converted into a Feature Request here https://github.com/serverpod/serverpod/issues/2798
