### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Dario-Ciceri** [serverpod/serverpod#2857]
**Describe the bug**
Calling the getAdmin method of my endpoint an exception occurs that reports null check operator used on a null value, however I don't understand how this is possible as I don't use the null check operator anywhere... I also tried applying a migration but nothing...

```
class: UserRole
table: user_role
fields:
  name: String
```

```
class: OfflineUser
table: user
fields:
  userInfo: module:auth:UserInfo?, relation
  role: UserRole?, relation(optional)

indexes:
  user_info_id_unique_idx:
    fields: userInfoId
    unique: true

```

`class UserEndpoint extends Endpoint { ... }`

```
Future<OfflineUser?> getAdmin(Session session) async {
    UserRole? adminRole = await UserRole.db.findFirstRow(
      session,
      where: (role) => role.name.equals('admin'),
    );

    if (adminRole == null) {
      await UserRole.db.insertRow(
          session, UserRole(name: 'admin'));
    }

    OfflineUser? admin = await OfflineUser.db.findFirstRow(session,
        where: (user) =>
            user.role.name.equals('admin'));

    return admin;
  }
```

error log:
```
#0      _getTableOrAssert (package:serverpod/src/database/adapters/postgres/database_connection.dart:733)
#1      DatabaseConnection.findFirstRow (package:serverpod/src/database/adapters/postgres/database_connection.dart:92)
#2      Database.findFirstRow (package:serverpod/src/database/database.dart:79)
#3      UserRoleRepository.findFirstRow (package:test_server/src/generated/user/user_role.dart:197)
#4      UserEndpoint.getAdmin (file:///app/lib/src/endpoints/user_endpoint.dart:250)
#5      Endpoints.initializeEndpoints.<anonymous closure> (file:///app/lib/src/generated/endpoints.dart:413)
#6      Server._handleUriCall (package:serverpod/src/server/server.dart:508)
<asynchronous suspension>
#7      Server._handleRequest (package:serverpod/src/server/server.dart:296)
<asynchronous suspension>
#8      Server._handleRequestWithErrorBoundary (package:serverpod/src/server/server.dart:185)
<asynchronous suspension>
```

**Serverpod versions**
 -  _CLI Version: 2.1.4
 - _Library version: 2.1.4

**Platform information**
I'm running the server on localhost

**Additional context**
-

**Comment by SandPod** [comment]
Hey @Dario-Ciceri!

Have you run `serverpod generate` after you added the "table" keyword to the "UserRole" model?

The point in the code where the null check assertion is happening suggest that the the necessary generated code that informs the database connector what table the model has is missing.

If you inspect your `protocol.dart` file for the server, does the method `getTableForType` contain an entry for the "UserRole" model?

**Comment by Dario-Ciceri** [comment]
> Hey @Dario-Ciceri!
> 
> Have you run `serverpod generate` after you added the "table" keyword to the "UserRole" model?
> 
> The point in the code where the null check assertion is happening suggest that the the necessary generated code that informs the database connector what table the model has is missing.
> 
> If you inspect your `protocol.dart` file for the server, does the method `getTableForType` contain an entry for the "UserRole" model?

Hi, yes I have and this is the protocol.dart

```
 @override
  _i1.Table? getTableForType(Type t) {
    {
      var table = _i3.Protocol().getTableForType(t);
      if (table != null) {
        return table;
      }
    }
    {
      var table = _i2.Protocol().getTableForType(t);
      if (table != null) {
        return table;
      }
    }
    switch (t) {
      case _i4.Ingredient:
        return _i4.Ingredient.t;
      case _i15.OfflineUser:
        return _i15.OfflineUser.t;
      case _i16.UserRole:
        return _i16.UserRole.t;
    }
    return null;
  }
```

If it helps, I created a new project and the exact same code works... I don't know, maybe I broke something in my configuration but even trying to make it as similar as the new project, the problem persists...

**Comment by Dario-Ciceri** [comment]
I solved it but without knowing exactly how... which is not exactly good... I made a new project, copied just the models and endpoints and it was going. At that point I took the server folder of the new project and overwritten it to the one in the corrupted project and now everything works fine... My guess is that I must have deleted or moved some important files for serverpod without realizing it and so the auto generated versions were not in line with the new changes. Could it be that by deleting the generated folder then everything can be corrupted? in any case it's going now, I'll wait to close the issue in case we want to explore this further to avoid it for others in the future

**Comment by SandPod** [comment]
>  ....I also noticed a further absurd problem that I didn't....(SortParams)

This also sounds like the model and the `protocol` file generated are not properly activated in the call stack of the endpoint.

Is there any chance that you might have imported the "client" version of the generated files in your endpoints? Or placed any other imports from the server towards the "client" package?

> I solved it but without knowing exactly how...

It would be great if we could explore what might have been the difference between your new project and the old one that become corrupted.

Did you make any changes to the `config/generator` file in your server package?

**Comment by Dario-Ciceri** [comment]
> > ....I also noticed a further absurd problem that I didn't....(SortParams)
> 
> This also sounds like the model and the `protocol` file generated are not properly activated in the call stack of the endpoint.
> 
> Is there any chance that you might have imported the "client" version of the generated files in your endpoints? Or placed any other imports from the server towards the "client" package?
> 
> > I solved it but without knowing exactly how...
> 
> It would be great if we could explore what might have been the difference between your new project and the old one that become corrupted.
> 
> Did you make any changes to the `config/generator` file in your server package?

With a difference comparator this is what I found:

new project:

bin\main.dart:
```
import 'package:test_server/server.dart';
```

lib\server.dart
```
import 'package:test_server/src/web/routes/root.dart';
```

user_endpoint:
```
import 'package:test_server/src/generated/protocol.dart';
```

###############################################

old project:

bin\main.dart:
```
import '../lib/server.dart';  **maybe the problem?**
```

lib\server.dart
```
import 'src/web/routes/root.dart';
```

user_endpoint:
```
import 'package:test_server/src/generated/ingredient/ingredient.dart';
import 'package:test_server/src/generated/user/user.dart';
```

**Comment by SandPod** [comment]
What happens if you change the import in the `user_endpoint` to use the `import 'package:test_server/src/generated/protocol.dart';` but keep the other imports?
Can you still replicate the issue?

And just to clarify, the name of your project  is `test` right?

**Comment by Dario-Ciceri** [comment]
> What happens if you change the import in the `user_endpoint` to use the `import 'package:test_server/src/generated/protocol.dart';` but keep the other imports? Can you still replicate the issue?
> 
> And just to clarify, the name of your project is `test` right?

no the name is not test, I used test to give a generic name here on github. The name shouldn't give any problems anyway I suppose but thanks for asking, I tried your suggestion but the error persists.

**Comment by SandPod** [comment]
In your `lib/server.dart`, do you have the following two imports?

```dart
import 'src/generated/endpoints.dart';
import 'src/generated/protocol.dart';
```

**Comment by Dario-Ciceri** [comment]
> In your `lib/server.dart`, do you have the following two imports?
> 
> ```dart
> import 'src/generated/endpoints.dart';
> import 'src/generated/protocol.dart';
> ```

yes.

**Comment by Dario-Ciceri** [comment]
mySharedPassword is different, but I don't think this is a problem, maybe? nothing else is different in Server and Client.

**Comment by SandPod** [comment]
> mySharedPassword is different, but I don't think this is a problem, maybe? nothing else is different in Server and Client.

This should not have any impact on the generated code.

> yes, I'm checking again the differences but the project is large and the process needs time to compare everything

I'm very grateful for you helping us debug this. 

Do you use `serverpod generate` with the `--watch` flag? If not, the code generator does not store any state between each time it is run. The files analyzed are the once that are used. So it should not be possible to end up with a "corrupted" state in your project.

How are you instantiating your Serveprod Class?
Is the `Protocol` class the one that is generated on the Server?

```dart
  // Initialize Serverpod and connect it with your generated code.
  final pod = Serverpod(
    args,
    Protocol(),
    Endpoints(),
  );
```

And just to sanity check,  are you compiling the project? If so, have you removed previous compiled versions of the server?

**Comment by Dario-Ciceri** [comment]
server.dart:

```
import 'package:serverpod/serverpod.dart';

import 'src/web/routes/root.dart';
import 'package:serverpod_auth_server/serverpod_auth_server.dart' as auth;

import 'src/generated/protocol.dart';
import 'src/generated/endpoints.dart';

// This is the starting point of your Serverpod server. In most cases, you will
// only need to make additions to this file if you add future calls,  are
// configuring Relic (Serverpod's web-server), or need custom setup work.

void run(List<String> args) async {
  // Initialize Serverpod and connect it with your generated code.
  final pod = Serverpod(
    args,
    Protocol(),
    Endpoints(),
    authenticationHandler: auth.authenticationHandler,
  );

  // If you are using any future calls, they need to be registered here.
  // pod.registerFutureCall(ExampleFutureCall(), 'exampleFutureCall');

  // Setup a default page at the web root.
  pod.webServer.addRoute(RouteRoot(), '/');
  pod.webServer.addRoute(RouteRoot(), '/index.html');
  // Serve all files in the /static directory.
  pod.webServer.addRoute(
    RouteStaticDirectory(serverDirectory: 'static', basePath: '/'),
    '/*',
  );
```
I use `serverpod generate --watch` and I tried `serverpod generate` without the `--watch` flag

> are you compiling the project?
I'm running everything with `dart bin/main.dart --apply-migrations` and I even used `flutter clean` and `pub dart get' on each folder

**Comment by SandPod** [comment]
This all sounds very strange.

> could it be that serverpod isn't using the new generated files?

That shouldn't be possible. This is all based on Dart handling the imports so it shouldn't be possible to use an older version of the same server as long as you restart your application.

I know that pub is having some issues with old CLI versions being cached but this shouldn't impact the service runtime: https://github.com/dart-lang/pub/issues/4295#issuecomment-2371670722

What OS are you using?

**Comment by Rokke** [comment]
I had a similar problem as above found this issue and just want to share my solution/findings

This problem happend for me when I updated to 2.1.5 from 2.1.4.
While doing the upgrade on my development environment (probably while running serverpod generate) I got a error in my server.dart file at
`final pod = Serverpod(
    args,
    Protocol(),
    Endpoints(),
    authenticationHandler: auth.authenticationHandler,
  );`
On the Protocol() line it complained that it didn't find it in my imports? (might have been because it was still generating or something).
Then I auto added a import suggestion to use auth.Protocol() instead, but after I did this and when I updated my staging environment all database queries in my endpoints failed (Table.db.count(), *.find() etc with this Null check operator used on a null value).
On my development environment it was working with this auth.Protocol()
After trying different things I rewerted the code to go back to only Protocol() instead of auth.Protocol() and then did a new serverpod generate and then moved this to my staging environment and everything worked again?

**Comment by SandPod** [comment]
Thanks for the additional information @Rokke!

If I understand you correctly the change you made resulted in your Serverpod instance being instantiated like this:

```dart
Serverpod(
  args,
  auth.Protocol(),
  Endpoints(),
  authenticationHandler: auth.authenticationHandler,
);
```

The difference is that `auth.Protocol()` is used instead of `Protocol().` 

This modification will cause unexpected behavior because you no longer use the protocol file generated for your project but rather the file generated for the `auth` module. This protocol file doesn't contain the required information to deserialize models defined in your project (or possibly other modules used by your project).

**Comment by Rokke** [comment]
Yes, and the reason for me changing it to auth.Protocol() was because Protocol() wasn't found in the imports (probably because of the generate or reindexing) and I was too impatient.
I just wanted to add this as a comment here in case someone else find this issue searching for the same error message (and did the same mistake)

**Comment by SandPod** [comment]
Small update, we recently fixed an issue where a model class naming collision with a module might have generated incorrect imports when combined with file load order from disk.

This could be a related issue to that where a collision with a module model or module alias might cause the wrong imports to be generated.

The "theoretical" issues where this might happen are tracked here: https://github.com/serverpod/serverpod/issues/3019

**Comment by SandPod** [comment]
I'm now fairly convinced that the root issue being displayed here is the result from #3019.

I'll close this issue in favour of that one.
