### ISSUE TITLE
Concurrent modification during iteration: Instance(length:17) of '_GrowableList'.

### ISSUE THREAD

**Issue by udiedrichsen** [serverpod/serverpod#2972]
**Describe the bug**

I tried to use chatgpt to generate serverpod model files for a new app. I teached serverpod with the 
https://github.com/serverpod/serverpod_docs/blob/main/docs/06-concepts/02-models.md

and my app idea. 

Chatgpt generated a bunch of .spy.yaml files which are looking good but makes serverpod generate crash with
Concurrent modification during iteration: Instance(length:17) of '_GrowableList'.

To simplify things it tried generate only the code for one this model files (I know that generated model files are not correct,
but it would be lovely to get an error message instead of an exception)

**To Reproduce**
1. serverpod create myapp

2. cd myapp;cd myapp_server

3. create inside lib/src/models/user.spy.yaml 
class: User
table: users
fields:
  id: int, isPrimaryKey, autoIncrement
  username: String, unique
  email: String, unique
  displayName: String
  calendarEvents: List<CalendarEvent>, relation
  createdAt: DateTime, default=now
  updatedAt: DateTime, default=now

4. serverpod generate
5. See error

Stack-Trace:
Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling.
We would appreciate if you filed an issue over at Github. Please include the stack trace below and
describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues

```
Concurrent modification during iteration: Instance(length:17) of '_GrowableList'.

#0      ListIterator.moveNext (dart:_internal/iterable.dart:348:7)
#1      ModelDependencyResolver.resolveModelDependencies.<anonymous closure>
(package:serverpod_cli/src/analyzer/models/entity_dependency_resolver.dart:17:51)
#2      Iterable.forEach (dart:core/iterable.dart:347:35)
#3      ModelDependencyResolver.resolveModelDependencies
(package:serverpod_cli/src/analyzer/models/entity_dependency_resolver.dart:15:51)
#4      SerializableModelAnalyzer.resolveModelDependencies
(package:serverpod_cli/src/analyzer/models/model_analyzer.dart:95:36)
#5      StatefulAnalyzer._updateAllModels
(package:serverpod_cli/src/analyzer/models/stateful_analyzer.dart:113:31)
#6      StatefulAnalyzer.validateAll
(package:serverpod_cli/src/analyzer/models/stateful_analyzer.dart:71:5)
#7      performGenerate (package:serverpod_cli/src/generator/generator.dart:29:25)
<asynchronous suspension>
#8      StdOutLogger.progress (package:cli_tools/src/logger/loggers/std_out_logger.dart:141:20)
<asynchronous suspension>
#9      GenerateCommand.run (package:serverpod_cli/src/commands/generate.dart:69:17)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     BetterCommandRunner.runCommand
(package:cli_tools/src/better_command_runner/better_command_runner.dart:140:7)
<asynchronous suspension>
#12     ServerpodCommandRunner.runCommand
(package:serverpod_cli/src/runner/serverpod_command_runner.dart:103:5)
```

**Expected behavior**
Instead of an exception I except to get an error message.

I figured out, the main reason for this exception is this:
calendarEvents: List<CalendarEvent>, relation

Deleting "List" from the line and I get an error message instead of the exception.

**Serverpod versions**
 -  _CLI Version:  2.1.5
 - _Library version: 2.1.5

**Platform information**
Apple MacBookPro M1

Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (4 weeks ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3

**Additional context**
Hope this helps, that took a while for figuring this out and open an issue.
This happens also on the latest 2.2.0 beta

Ok, I also learned that I have to feed the AI with https://github.com/serverpod/serverpod_docs/tree/main/docs/06-concepts/06-database/03-relations

**Comment by Isakdl** [comment]
Thank you for the report!

```yaml
calendarEvents: List, relation
```
As. you pointed out List alone doesn't work, you need to put the type into the list as well.
E.g. `List<MyClass>`

Another problem in your yaml is the following:

```
username: String, unique
```

`unique` is not a valid keyword here (yet).

With that said this is clearly a bug, the linter shouldn't crash because of a typo.

**Comment by udiedrichsen** [comment]
Thanks for the fast response.  Regarding unique (from the docs):

unique: Boolean flag to make the entries unique in the database.

I tried it again and I trained the AI with the correct documentation and it generated 17 model files.
All were succesfull  parsed by serverpod generate and I got only 3 errors which are easy to fix.
