### ISSUE TITLE
Socket error: Bad state: Message parser consumed more bytes than expected

### ISSUE THREAD

**Issue by starklord** [serverpod/serverpod#3075]
Hi, in the latest version of serverpod 2.3.0 i have the issue when i query many rows from my database:
instance of '_PgDatabaseQueryException'
#0      DatabaseConnection._query (package:serverpod/src/database/adapters/postgres/database_connection.dart:429:7)
<asynchronous suspension>
#1      DatabaseConnection._mappedResultsQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:482:18)
<asynchronous suspension>
#2      DatabaseConnection._deserializedMappedQuery (package:serverpod/src/database/adapters/postgres/database_connection.dart:505:18)
<asynchronous suspension>
#3      ScheduleService.listAttendances (package:eva_erp_server/src/endpoints/hr/schedule_service.dart:30:18)
<asynchronous suspension>
#4      Server._handleUriCall (package:serverpod/src/server/server.dart:508:20)
<asynchronous suspension>
#5      Server._handleRequest (package:serverpod/src/server/server.dart:296:18)
<asynchronous suspension>
#6      Server._handleRequestWithErrorBoundary (package:serverpod/src/server/server.dart:185:5)
<asynchronous suspension>

when i run locally in my laptop i have no issue, but when i run on my VPS server i get that error. Maybe there is some configuration i have to do ? but just for your information, in other serverpod versions i didnt have this error.
many thanks.

**Comment by starklord** [comment]
I downgraded from 2.3.0 to 2.2.2 and the error description is more accurated:
DatabaseException: Socket error: Bad state: Message parser consumed more bytes than expected. type=68 expectedLength=493

**Comment by SandPod** [comment]
Hey @starklord!

First question: We added a database exception object in 2.3.0 with the sole purpose of providing more details if a database exception occurs. When the exception was printed, was there no details included?

If so, we might have a bug there that needs to be fixed.

Any chance that you also upgraded the postgres driver when upgrading Serverpod?

There seems to be an issue with long running queries that has since then been fixed: https://github.com/isoos/postgresql-dart/issues/395

Try using Postgres version 3.4.5 or later and see if you can reproduce the issue: https://pub.dev/packages/postgres/versions

**Comment by starklord** [comment]
Thank you so much! the problem has been solved changing postgresql plugin version to the latest (^3.4.8)

**Comment by SandPod** [comment]
@starklord Glad to hear!

> First question: We added a database exception object in 2.3.0 with the sole purpose of providing more details if a database exception occurs. When the exception was printed, was there no details included?

It would be great to get your input on this as well 👆, was there no information included in the error print?

**Comment by SandPod** [comment]
I fixed the issue with insufficient prints, this will be included in the next release of Serverpod.
