### ISSUE TITLE
generate watch doesn't work as expected.

### ISSUE THREAD

**Issue by yahu1031** [serverpod/serverpod#323]
## Description
I was watching the changes and generating the client-side code with the following command `serverpod generate --watch`. If there is any compile-time error while writing a function, The watch breaks with the error mentioned below.

```console
➜  mypod_server serverpod generate --watch
Running serverpod generate.
Initial code generation complete. Listening for changes.
File changed: add lib/src/endpoints/employee_endpoint.dart
Running serverpod generate.
Incremental code generation complete.

File changed: modify lib/src/endpoints/employee_endpoint.dart
Running serverpod generate.
Incremental code generation complete.

File changed: modify lib/src/endpoints/employee_endpoint.dart
Running serverpod generate.
Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if you filed an issue over at Github. Please include the stack trace below and describe any steps you
did to trigger the error.
https://github.com/serverpod/serverpod/issues
RangeError (index): Invalid value: Valid value range is empty: 0
#0      _StringBase.[] (dart:core-patch/string_patch.dart:260:41)
#1      ProtocolAnalyzer._formatEndpointName (file:///Users/mr.minnu/Documents/Flutter/serverpod/tools/serverpod_cli/bin/generator/protocol_analyzer.dart:257:36)
#2      ProtocolAnalyzer.analyze (file:///Users/mr.minnu/Documents/Flutter/serverpod/tools/serverpod_cli/bin/generator/protocol_analyzer.dart:123:32)
<asynchronous suspension>
#3      performAnalyzeServerCode (file:///Users/mr.minnu/Documents/Flutter/serverpod/tools/serverpod_cli/bin/generator/protocol_analyzer.dart:54:10)
<asynchronous suspension>
#4      performGenerate (file:///Users/mr.minnu/Documents/Flutter/serverpod/tools/serverpod_cli/bin/generator/generator.dart:51:28)
<asynchronous suspension>
#5      _performGenereateProtocolContinuously (file:///Users/mr.minnu/Documents/Flutter/serverpod/tools/serverpod_cli/bin/generator/generator_continuous.dart:33:5)
<asynchronous suspension>
```

**NOTE:** This mainly happens while writing the return types to the functions in Endpoint.

**Comment by yahu1031** [comment]
And also it is not watching the generator 😞 after those trace logs

**Comment by yahu1031** [comment]
lemme cross-check and update this ticket.

**Comment by yahu1031** [comment]
https://user-images.githubusercontent.com/35523357/197688788-674ca217-93a7-4ad0-b802-9273285f9e40.mp4

It never watches again
