### ISSUE TITLE
Recreate missing folders of project structure when you run "serverpod generate"

### ISSUE THREAD

**Issue by AndryHTC** [serverpod/serverpod#336]
I've deleted the **serverpod_server/lib/src/generated** folder for cleaning older files.

On "serverpod generate" it retrieves

```
Running serverpod generate.
Failed to generate lib/src/generated/soggetto_entity.dart
Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if you filed an issue over at Github. Please
include the stack trace below and describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues
FileSystemException: Cannot create file, path = 'lib/src/generated/soggetto_entity.dart' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ClassGenerator.generate (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/generator/class_generator.dart:61:20)
#3      performGenerateClasses (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/generator/class_generator.dart:23:19)
#4      performGenerate (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/generator/generator.dart:36:3)
#5      _main (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/serverpod_cli.dart:201:13)
<asynchronous suspension>
#6      main.<anonymous closure> (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/serverpod_cli.dart:33:9)
<asynchronous suspension>
#7      main (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/serverpod_cli.dart:30:3)
<asynchronous suspension>


Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if you filed an issue over at Github. Please
include the stack trace below and describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues
FileSystemException: Cannot create file, path = 'lib/src/generated/protocol.dart' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.createSync (dart:io/file_impl.dart:273:5)
#2      ClassGenerator.generate (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/generator/class_generator.dart:74:13)
#3      performGenerateClasses (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/generator/class_generator.dart:23:19)
#4      performGenerate (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/generator/generator.dart:36:3)
#5      _main (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/serverpod_cli.dart:201:13)
<asynchronous suspension>
#6      main.<anonymous closure> (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/serverpod_cli.dart:33:9)
<asynchronous suspension>
#7      main (file:///Users/andry/.pub-cache/hosted/pub.dartlang.org/serverpod_cli-0.9.19/bin/serverpod_cli.dart:30:3)
<asynchronous suspension>
```
recreating the **serverpod_server/lib/src/generated** folder fixes the problem. When someone accidentally delete optional folders that are not directly correlated to the core function of serverpod, serverpod should recreate them.

BTW I love Serverpod <3

**Comment by yahu1031** [comment]
@AndryHTC Ideally they must create if they don't exist. Can you able to recreate this with the latest version?

**Comment by AndryHTC** [comment]
@yahu1031 I didn't try but I didn't see any change about it either. Just follow the 2 steps to reproduce the issue and if it's fixed I will close the issue 👍

**Comment by yahu1031** [comment]
Okie, lemme try.

**Comment by yahu1031** [comment]
@AndryHTC I have tested it and it was fixed.
```console
mr.minnu@Tradelabs-MacBook-Pro-2 hey_server % cd lib/src/
mr.minnu@Tradelabs-MacBook-Pro-2 src % rm -rf generated/
mr.minnu@Tradelabs-MacBook-Pro-2 src % cd ../..
mr.minnu@Tradelabs-MacBook-Pro-2 hey_server % serverpod generate
Running serverpod generate.
Done.
mr.minnu@Tradelabs-MacBook-Pro-2 hey_server % ls lib/src/
endpoints    future_calls generated    protocol     web
mr.minnu@Tradelabs-MacBook-Pro-2 hey_server % 
```

**Comment by yahu1031** [comment]
So the thing when you are using this and the errors happened is that we don't have file/dir creation on recursion mode. Now the latest have the recursion everywhere. So, even if the folder doesn't exist, due to the recursion, the parent will be automatically generated.

**Comment by AndryHTC** [comment]
@yahu1031, your contribution is greatly appreciated. Thank you for taking the time to test and verify the issue. I will now proceed to close this issue.
