### ISSUE TITLE
Waiting for Postgres... while i run serverpod create mypod

### ISSUE THREAD

**Issue by mahmoudelgharabawi** [serverpod/serverpod#420]
I Faced This issue on Linux Ubuntu

![Screenshot from 2022-11-29 22-25-45](https://user-images.githubusercontent.com/37341935/204641147-499619dc-97aa-4808-b186-84337f0f6538.png)

this happen when i run this command 

serverpod create mypod

is there any solution for this  ???!!!!

**Comment by yahu1031** [comment]
That means that 8090 port is being used by some other services. Stop it and try again, things will work fine.

**Comment by mahmoudelgharabawi** [comment]
I checked No Services Running on port 8090 ???

**Comment by yahu1031** [comment]
Can you cross-check with this command `netstat -tna | grep 'LISTEN'`

**Comment by mahmoudelgharabawi** [comment]
There is No Port 8090 on it

**Comment by yahu1031** [comment]
strange, Lemme check.

**Comment by yahu1031** [comment]
@mahmoudelgharabawi Can you do one thing(Just a try)

stop it and in `setup-tables` file change the `Line 7-18` and run the script again with docker up.

```diff
- if command -v netstat &> /dev/null
- then
-   while ! netstat -tna | grep 'LISTEN' | grep -q '.8090'; do
-     echo "Waiting for Postgres..."
-     sleep 2 # time in seconds, tune it as needed
-   done
- else
-   while ! ss -tulpn | grep LISTEN | grep :8090; do
-     echo "Waiting for Postgres..."
-     sleep 2
-   done
- fi

+ while lsof -Pi :8090 -sTCP:LISTEN -t >/dev/null ; do
+   echo "Waiting for Postgres..."
+   sleep 2 # time in seconds, tune it as needed
+ done
```

**Comment by mahmoudelgharabawi** [comment]
@yahu1031  

Sry i can't understand what you mean ?!

**Comment by mahmoudelgharabawi** [comment]
@yahu1031 

this what i get 

./setup-tables
Starting docker
/snap/docker/2285/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
Traceback (most recent call last):
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/docker/2285/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/command.py", line 70, in project_from_options
    enabled_profiles=get_profiles_from_options(options, environment)
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/command.py", line 153, in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/docker_client.py", line 43, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
    f'Error while fetching server API version: {e}'
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
Postgres is ready
/snap/docker/2285/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
Traceback (most recent call last):
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/docker/2285/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/command.py", line 70, in project_from_options
    enabled_profiles=get_profiles_from_options(options, environment)
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/command.py", line 153, in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/docker_client.py", line 43, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
    f'Error while fetching server API version: {e}'
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
Stopping docker
/snap/docker/2285/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
Traceback (most recent call last):
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/snap/docker/2285/lib/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/snap/docker/2285/usr/lib/python3.6/http/client.py", line 984, in send
    self.connect()
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/docker/2285/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/command.py", line 70, in project_from_options
    enabled_profiles=get_profiles_from_options(options, environment)
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/command.py", line 153, in get_project
    verbose=verbose, version=api_version, context=context, environment=environment
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/docker_client.py", line 43, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/snap/docker/2285/lib/python3.6/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/snap/docker/2285/lib/python3.6/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
    f'Error while fetching server API version: {e}'
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))

**Comment by yahu1031** [comment]
@mahmoudelgharabawi could you ping me in twitter if possible

**Comment by yahu1031** [comment]
@mahmoudelgharabawi This is because your docker-compose needs sudo access. For time being and as of not a serverpod issue, please edit your `.serverod/VERSION/serverpod_template/projectname_server/setup-tables` file

from this 👇🏻 

```sh
...
docker-compose ***
...
```

to 👇🏻 

```sh
...
sudo docker-compose ***
...
```
everywhere. Hope this resolves your issue. If it does, please close this issue as solved 😃

**Comment by mahmoudelgharabawi** [comment]
When i do so the problem of creating serverpod project salved 

But When i use this command

dart bin/main.dart


it Can't Find The Table Also......


the I use BeeKeeper Studio to add tables manually (I think in this point the issue is closed .)

**Comment by hiro2016** [comment]
Had some trouble running serverpod on ubuntu22 LTS 

### Some commands were not available.     
``` 
sudo apt install net-tools docker docker-compose  
```    

### No edits needed.  
  
```
systemctl --user start docker-desktop  
serverpod create mypod  
cd ./mypod/mypod_server
docker-compose up --build --detach  
dart bin/main.dart
```
