### ISSUE TITLE
 Sign in with Google  ServerpodClientException

### ISSUE THREAD

**Issue by tusharbhambere** [serverpod/serverpod#465]
this Error Coming in Console

Failed call: serverpod_auth.google.authenticateWithServerAuthCode
I/flutter (28704): ServerpodClientException: Internal server error. Call log id: 112, statusCode = 500
I/flutter (28704): serverpod_auth_google: ServerpodClientException: Internal server error. Call log id: 112, statusCode = 500

followed All Step Required For Google Authentication
Generated Table as in Documentation
Enable Public Api and all Google Console Setup 
also Pasted  google_client_secret.json file in server>config
added All Dependency Required Both Side flutter, server client side

**Comment by yahu1031** [comment]
@tusharbhambere Can you please post the data of `id: 112` from the server log table?

**Comment by tusharbhambere** [comment]
{
  "id": 112,
  "serverId": "default",
  "time": "2022-12-10 13:25:11.444132",
  "module": null,
  "endpoint": "serverpod_auth.google",
  "method": "authenticateWithServerAuthCode",
  "duration": 0.000345,
  "numQueries": 0,
  "slow": false,
  "error": "Null check operator used on a null value",
  "stackTrace": "#0      GoogleEndpoint.authenticateWithServerAuthCode (package:serverpod_auth_server/src/endpoints/google_endpoint.dart:34:30)\n#1      Endpoints.initializeEndpoints.<anonymous closure> (package:serverpod_auth_server/src/generated/endpoints.dart:332:20)\n#2      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:111:37)\n<asynchronous suspension>\n#3      Server._handleRequest (package:serverpod/src/server/server.dart:221:18)\n<asynchronous suspension>\n",
  "authenticatedUserId": null,
  "isOpen": null,
  "touched": "2022-12-10 13:25:11.444132"
}

**Comment by yahu1031** [comment]
> `"error": "Null check operator used on a null value",`
> > `GoogleEndpoint.authenticateWithServerAuthCode`

@tusharbhambere Can you trace it out where?

**Comment by tusharbhambere** [comment]
Above Error Solve Its Coming beacause  config/google_client_secret.json in this file client_secret and redirect_uris not present i solved by creating new web application and replaced json 

but now this error coming i already try app to go in production as well as i added testing mail 

Failed to obtain access credentials. Error: invalid_request 
You can&#39;t sign in to this app because it doesn&#39;t comply with Google&#39;s OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn&#39;t comply with one or more Google validation rules.
   Status code: 400
#0      ClientExtensions.requestJson (package:googleapis_auth/src/utils.dart:101:7)
<asynchronous suspension>
#1      obtainAccessCredentialsViaCodeExchange (package:googleapis_auth/src/oauth2_flows/auth_code.dart:115:19)
<asynchronous suspension>
#2      _GoogleUtils.clientViaClientSecretAndCode (package:serverpod_auth_server/src/endpoints/google_endpoint.dart:231:23)
<asynchronous suspension>
#3      GoogleEndpoint.authenticateWithServerAuthCode (package:serverpod_auth_server/src/endpoints/google_endpoint.dart:33:22)
<asynchronous suspension>
#4      EndpointDispatch.handleUriCall (package:serverpod/src/server/endpoint_dispatch.dart:111:20)
<asynchronous suspension>
#5      Server._handleRequest (package:serverpod/src/server/server.dart:221:18)
<asynchronous suspension>

**Comment by yahu1031** [comment]
Hmmm, Then it sounds like the configs are not set properly.

**Comment by tusharbhambere** [comment]
Issue Fixed with Serverpod 0.9.21
