### ISSUE TITLE
type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by mklimko-perpetio** [serverpod/serverpod#537]
I have stream connection and all was good. After adding some extra logic and classes to endpoints I get this when I try to send stream message
```
type 'Null' is not a subtype of type 'String'
#0      Server._handleWebsocket (package:serverpod/src/server/server.dart:395:43)
<asynchronous suspension>
```
this exception lead me to serverpod lib to this line 
<img width="735" alt="image" src="https://user-images.githubusercontent.com/96616581/210228045-658d14d1-8005-4018-902c-997328d435c1.png">
so className property now is null, but why? this is database class and it was generated by serverpod from yaml so Idk what can cause this 

I printed json that come to websocket right before it throw exception and I got this:
```
INFO: {"command":"ping","args":{}}
INFO: {"endpoint":"room","object":{"className":null,"data":{"id":null,"roomId":"","userId":2,"messageType":"message","text":"testMessage","createdAt":"2023-01-02T12:03:07.456407Z"}}}
type 'Null' is not a subtype of type 'String'
#0      Server._handleWebsocket (package:serverpod/src/server/server.dart:395:43)
<asynchronous suspension>
```

**Comment by mklimko-perpetio** [comment]
Finally I found issue, in one file of project_name_flutter part I made wrong import and it caused wrong serialization.
I imported
`import 'package:project_name_server/project_name_server.dart';`
instead of 
`import 'package:project_name_client/project_name_client.dart';`
So, I changed import to second variant and it fixed my issue
