### ISSUE TITLE
`parent=` can't reference a table from a module

### ISSUE THREAD

**Issue by fischerscode** [serverpod/serverpod#695]
**Describe the bug**
When referencing a table from a module as a parent, an error is thrown.

**To Reproduce**
1. `serverpod create ...`
2. Add auth module
3. Add `  user: int, parent=serverpod_user_info` to `example.yaml`.
4. `serverpod generate`
5. See error

<details>
<summary>Error</summary>

```

WARNING! Windows is not officially supported yet. Things may or may not work as expected.

Running serverpod generate.
Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We
would appreciate if you filed an issue over at Github. Please include the stack trace below and describe
any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues
FormatException: The table "example" (class "Example" is referencing a table that doesn't exist (serverpod_user_info).)
#0      PgsqlGenerator._sortClassInfos (**/pub.dev/serverpod_cli-1.0.1/bin/generator/pgsql_generator.dart:69:15)
#1      PgsqlGenerator.generate (**/pub.dev/serverpod_cli-1.0.1/bin/generator/pgsql_generator.dart:22:5)
#2      ClassGenerator.generate (**/pub.dev/serverpod_cli-1.0.1/bin/generator/class_generator.dart:97:22)
#3      performGenerateClasses (**/pub.dev/serverpod_cli-1.0.1/bin/generator/class_generator.dart:29:19)
#4      performGenerate (**/pub.dev/serverpod_cli-1.0.1/bin/generator/generator.dart:56:3)
<asynchronous suspension>
#5      _main (**/pub.dev/serverpod_cli-1.0.1/bin/serverpod_cli.dart:201:7)
<asynchronous suspension>
#6      main.<anonymous closure> (**/pub.dev/serverpod_cli-1.0.1/bin/serverpod_cli.dart:33:9)
<asynchronous suspension>
#7      main (**/pub.dev/serverpod_cli-1.0.1/bin/serverpod_cli.dart:30:3)
<asynchronous suspension>

```

</details>

**Expected behavior**
Adds foreign key.

**Screenshots**
N/A

**Serverpod versions**
 -  _CLI Version:_ 1.0.1
 - _Library version:_ 1.0.1

**Platform information**
Windows

**Additional context**
Thrown here: https://github.com/serverpod/serverpod/blob/70473726427c4989ef0506473c08412a97cff80e/tools/serverpod_cli/bin/generator/pgsql_generator.dart#L68-L70
Somehow related to #653.

**Comment by Isakdl** [comment]
Tracking this issue here instead: #984
