### ISSUE TITLE
"Failed to read body of request" error thrown occasionally

### ISSUE THREAD

**Issue by bselwe** [serverpod/serverpod#806]
Hi @vlidholt. Our server (with around 200 active users) throws internal server errors with "Failed to read body of request" messages from time to time. It happens for either Serverpod or custom endpoints (e.g. for Serverpod's [`StatusEndpoint`](https://github.com/serverpod/serverpod/blob/release-0.9.18/modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/status_endpoint.dart#L11)). The server is running in a Docker container on AWS, with Dart 2.19.2, Serverpod 0.9.18, and `--old_gen_heap_size=0` to encourage garbage collection more aggresively.

These errors do not cause the server to crash but they happen daily. Do you have any idea what might they be related to? There's no way to catch them as they are logged internally by Serverpod. I am attaching the error details below.

<details>
<summary><b>Internal server error. Failed to read body of request. (Serverpod's endpoint)</b></summary>
<pre>
2023-04-05 10:44:29.688182Z Internal server error. Failed to read body of request.
--
  | HttpException: Connection closed while receiving data, uri = /serverpod_auth.status
  | #0 _HttpIncoming.listen.<anonymous closure> (dart:_http/http_impl.dart:441:7)
  | #1 Stream.handleError.<anonymous closure> (dart:async/stream.dart:929:16)
  | #2 _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269:17)
  | #3 _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
  | #4 _rootRunBinary (dart:async/zone.dart:1422:47)
  | #5 _CustomZone.runBinary (dart:async/zone.dart:1314:19)
  | #6 _CustomZone.runBinaryGuarded (dart:async/zone.dart:1224:7)
  | #7 _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
  | #8 _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
  | #9 _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
  | #10 _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:778:19)
  | #11 _StreamController._addError (dart:async/stream_controller.dart:656:7)
  | #12 _StreamController.addError (dart:async/stream_controller.dart:610:5)
  | #13 _HttpParser._reportBodyError (dart:_http/http_parser.dart:1176:22)
  | #14 _HttpParser._onDone (dart:_http/http_parser.dart:885:9)
  | #15 _rootRun (dart:async/zone.dart:1390:47)
  | #16 _CustomZone.run (dart:async/zone.dart:1300:19)
  | #17 _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
  | #18 _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
  | #19 _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
  | #20 _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
  | #21 _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
  | #22 _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
  | #23 _StreamController.close (dart:async/stream_controller.dart:630:5)
  | #24 _Socket._onData (dart:io-patch/socket_patch.dart:2362:21)
  | #25 _rootRunUnary (dart:async/zone.dart:1414:13)
  | #26 _CustomZone.runUnary (dart:async/zone.dart:1307:19)
  | #27 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
  | #28 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
  | #29 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
  | #30 _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
  | #31 _StreamController._add (dart:async/stream_controller.dart:648:7)
  | #32 _StreamController.add (dart:async/stream_controller.dart:596:5)
  | #33 new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1884:35)
  | #34 _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1327:18)
  | #35 _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
  | #36 _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
  | #37 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
  | #38 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
</pre>
</details>

<details>
<summary><b>Internal server error. Failed to read body of request. (Custom endpoint)</b></summary>
<pre>
HttpException: Connection closed while receiving data, uri = /workspaceUpdates
--
  | #0 _HttpIncoming.listen.<anonymous closure> (dart:_http/http_impl.dart:441:7)
  | #1 Stream.handleError.<anonymous closure> (dart:async/stream.dart:929:16)
  | #2 _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269:17)
  | #3 _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
  | #4 _rootRunBinary (dart:async/zone.dart:1422:47)
  | #5 _CustomZone.runBinary (dart:async/zone.dart:1314:19)
  | #6 _CustomZone.runBinaryGuarded (dart:async/zone.dart:1224:7)
  | #7 _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
  | #8 _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
  | #9 _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
  | #10 _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:778:19)
  | #11 _StreamController._addError (dart:async/stream_controller.dart:656:7)
  | #12 _StreamController.addError (dart:async/stream_controller.dart:610:5)
  | #13 _HttpParser._reportBodyError (dart:_http/http_parser.dart:1176:22)
  | #14 _HttpParser._onDone (dart:_http/http_parser.dart:885:9)
  | #15 _rootRun (dart:async/zone.dart:1390:47)
  | #16 _CustomZone.run (dart:async/zone.dart:1300:19)
  | #17 _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
  | #18 _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
  | #19 _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
  | #20 _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
  | #21 _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:782:19)
  | #22 _StreamController._closeUnchecked (dart:async/stream_controller.dart:637:7)
  | #23 _StreamController.close (dart:async/stream_controller.dart:630:5)
  | #24 _Socket._onData (dart:io-patch/socket_patch.dart:2362:21)
  | #25 _rootRunUnary (dart:async/zone.dart:1414:13)
  | #26 _CustomZone.runUnary (dart:async/zone.dart:1307:19)
  | #27 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
  | #28 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
  | #29 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
  | #30 _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
  | #31 _StreamController._add (dart:async/stream_controller.dart:648:7)
  | #32 _StreamController.add (dart:async/stream_controller.dart:596:5)
  | #33 new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1884:35)
  | #34 _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1327:18)
  | #35 _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
  | #36 _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
  | #37 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
  | #38 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
</pre>
</details>

**Comment by SandPod** [comment]
Are you still having this issue?
Do you get any traces of these requests in the client as well?

This could be caused by the HTTP connection being prematurely terminated when bigger payloads are being transfered.

**Comment by SandPod** [comment]
Closing this issue because of inactivity, please let us know if this is still an issue.
