### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by damienissa** [serverpod/serverpod#818]
**Describe the bug**
I have a GCP server where I released the Serverpod server using Terraform. And I have a problem. Locally it works fine!

Build command:
```yaml
name: Build the Docker image
working-directory: gaia_mobile_server
run: "docker build --build-arg runmode=${{env.TARGET}} -t $IMAGE_NAME ."
```

Docker file:
```go
FROM dart:2.19.0 AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/main.dart -o bin/main

FROM busybox

ARG runmode
ENV serverid=default
ENV logging=normal
ENV role=monolith

COPY --from=build /runtime/ /
COPY --from=build /app/bin/main /app/bin/main
COPY --from=build /app/config/ config/
COPY --from=build /app/generated/ generated/
COPY --from=build /app/web/ web/

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

CMD app/bin/main --mode $runmode --server-id $serverid --logging $logging --role $role

```

I have an issue when I'm running my server.

```console
Null check operator used on a null value
#0      new DatabaseConfig._ (package:serverpod_shared/src/config.dart:142)
#1      new ServerpodConfig (package:serverpod_shared/src/config.dart:61)
#2      new Serverpod (package:serverpod/src/server/serverpod.dart:242)
#3      run (package:gaia_mobile_server/server.dart:16)
#4      main (file:///app/bin/main.dart:12)
<asynchronous suspension>
```
Also, I have these messages in my Docker container logs:
```console
Unknown run mode, defaulting to development
```

## If I tried to make the same lines as crushed manually it works:
```dart
final file = 'config/${args[1]}.yaml';
    var data = File(file).readAsStringSync();
    var doc = loadYaml(data);
    Map dbSetup = doc['database'];
    final host = dbSetup['host'];
    final port = dbSetup['port'];
    final name = dbSetup['name'];
    final user = dbSetup['user'];
    print(
        "DATA BASE SETUP: host: $host, port: $port, name: $name, user: $user");
``` 
Output:
```console
DATA BASE SETUP: host: staging-database.mvp-gaia.com, port: 5432, name: serverpod, user: postgres
```

**Serverpod versions**
 -  serverpod_cli: ^1.0.1
 - serverpod: ^1.0.1

**Comment by SandPod** [comment]
Hey @damienissa!

Is this still an issue?
If so, I believe we have some better logging for our configuration now. If you could try this again we might be able to help you further.

One thing to keep in mind is to ensure that the process running serverpod is allowed to read the configuration file.

**Comment by christerswahn** [comment]
There are no longer any null check operators in this file, closing this as fixed.
