### ISSUE TITLE
Null check operator used on a null value white using serverpod generate

### ISSUE THREAD

**Issue by mrDLSable** [serverpod/serverpod#963]
**Describe the bug**
While using serverpod generate on a project with the following code, I get the following error:

In example_endpoint.dart, I added this in the ExampleEndpoint class:
```Dart
  Future<Article> test(Session session) async{
    return Article(
      title: 'Test Title',
    );
  }
```

I added article.yaml in the protocol folder with the following content:
```yaml
class: Article
fields:
  title: String
```

This is the output from serverpod generate:
```
WARNING! Windows is not officially supported yet. Things may or may not work as expected.

Yikes! It is possible that this error is caused by an internal issue with the Serverpod tooling. We would appreciate if you filed an issue over at Github. Please include the stack trace below and describe any steps you did to trigger the error.
https://github.com/serverpod/serverpod/issues
Null check operator used on a null value
#0      new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:75:49)
#1      new TypeDefinition.fromDartType.<anonymous closure> (package:serverpod_cli/src/generator/types.dart:70:56)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:47:28)
#7      ListIterable.toList (dart:_internal/iterable.dart:214:7)
#8      new TypeDefinition.fromDartType (package:serverpod_cli/src/generator/types.dart:70:73)
#9      EndpointsAnalyzer.analyze (package:serverpod_cli/src/analyzer/dart/endpoints_analyzer.dart:168:48)
<asynchronous suspension>
#10     performGenerate (package:serverpod_cli/src/generator/generator.dart:46:19)
<asynchronous suspension>
#11     _main (file:///C:/Users/dschu/AppData/Local/Pub/Cache/hosted/pub.dev/serverpod_cli-1.1.1/bin/serverpod_cli.dart:221:7)
<asynchronous suspension>
#12     main.<anonymous closure> (file:///C:/Users/dschu/AppData/Local/Pub/Cache/hosted/pub.dev/serverpod_cli-1.1.1/bin/serverpod_cli.dart:36:9)
<asynchronous suspension>
#13     main (file:///C:/Users/dschu/AppData/Local/Pub/Cache/hosted/pub.dev/serverpod_cli-1.1.1/bin/serverpod_cli.dart:33:3)
<asynchronous suspension>
```

**To Reproduce**
1. Be on Windows
2. Create a new empty project
3. Add the provided code
4. Run serverpod generate
5. See error

**Expected behavior**
Code should be generated for the client to use.

**Serverpod versions**
 -  _CLI Version:_ 1.1.1
 - _Library version:_ ^1.1.1

**Platform information**
Windows 11, latest updates. WSL is Ubuntu.

**Additional context**
I'm a serverpod noob (just started playing with it today), and couldn't figure out what to do with my google fu, but the CLI said to report it here, so here I am.

**Comment by Isakdl** [comment]
Just ran a test on this. 

The issue is that you have not imported the `Article` class into your Endpoint file. Put `import '../generated/article.dart';` at the top of the `example_endpoint.dart` and you should be able to get things to work.

The generate command would also work if you simply delete this code:
```dart
Future<Article> test(Session session) async{
  return Article(
    title: 'Test Title',
  );
}
```
Since that would remove the reference to the class we cannot find.


With that said this error is a bug on Windows, we should give a better error message here rather than crash on a null pointer. So thank you very much for the report! :).

**Comment by mrDLSable** [comment]
Thanks for the help. I didn't know you had to explicitly import the file. More explicit error messages would certainly be very helpful. I'll test your solution once I can find a moment to get in front of my PC.

**Comment by mrDLSable** [comment]
Thanks. Awesome to see you implement a fix so fast. Your fix did indeed work and I'm now happily exploring Serverpod once again.
